# -*- coding: utf-8 -*-
"""Copy of pandas-exercises.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PfyFLa-ppfgBOLC32F3_qd-dF5V6qFxT

# Pandas Practice

This notebook is dedicated to practicing different tasks with pandas. The solutions are available in a solutions notebook, however, you should always try to figure them out yourself first.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to pandas notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/).
"""

# Import pandas
import pandas as pd

# Create a series of three different colours
colors = pd.Series(['red', 'yellow', 'green'])

colors# View the series of different colours

# Create a series of three different car types and view it
cars = pd.Series(['BMW', 'Camero', 'Audi'])

# Combine the Series of cars and colours into a DataFrame
car_cat = pd.DataFrame({"Cars":cars,"Color": colors})
car_cat

# Import "../data/car-sales.csv" and turn it into a DataFrame
car_sales = pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/car-sales.csv")
car_sales

"""**Note:** Since you've imported `../data/car-sales.csv` as a DataFrame, we'll now refer to this DataFrame as 'the car sales DataFrame'."""

# Export the DataFrame you created to a .csv file
car_sales.to_csv("exported_car_sale.csv")

# Find the different datatypes of the car data DataFrame
car_sales.dtypes

# Describe your current car sales DataFrame using describe()
car_sales.describe()

# Get information about your DataFrame using info()
car_sales.info()

"""What does it show you?"""

# Create a Series of different numbers and find the mean of them
car_sales.mean()

# Create a Series of different numbers and find the sum of them
pd.Series([1100,1200,13000]).sum()

# List out all the column names of the car sales DataFrame
car_sales.columns

# Find the length of the car sales DataFrame
len(car_sales)

# Show the first 5 rows of the car sales DataFrame
car_sales.head()

# Show the first 7 rows of the car sales DataFrame
car_sales.head(7)

# Show the bottom 5 rows of the car sales DataFrame
car_sales.tail()

# Use .loc to select the row at index 3 of the car sales DataFrame
car_sales.tail().iloc[3]

# Use .iloc to select the row at position 3 of the car sales DataFrame
car_sales.iloc[3]

"""Notice how they're the same? Why do you think this is?

Check the pandas documentation for [.loc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html) and [.iloc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html). Think about a different situation each could be used for and try them out.
"""

# Select the "Odometer (KM)" column from the car sales DataFrame
car_sales["Odometer (KM)"]

# Find the mean of the "Odometer (KM)" column in the car sales DataFrame
car_sales["Odometer (KM)"].mean()

# Select the rows with over 100,000 kilometers on the Odometer
car_sales[car_sales["Odometer (KM)"]>100000]

# Create a crosstab of the Make and Doors columns
pd.crosstab(car_sales["Make"], car_sales["Doors"])

# Group columns of the car sales DataFrame by the Make column and find the average
car_sales.groupby(["Make"]).mean()

# Commented out IPython magic to ensure Python compatibility.
# Import Matplotlib and create a plot of the Odometer column
# Don't forget to use %matplotlib inline
# %matplotlib inline
car_sales["Odometer (KM)"].plot()

# Create a histogram of the Odometer column using hist()
car_sales["Odometer (KM)"].hist()

# Try to plot the Price column using plot()
car_sales = pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/car-sales.csv")
car_sales["Price"]

"""Why didn't it work? Can you think of a solution?

You might want to search for "how to convert a pandas string column to numbers".

And if you're still stuck, check out this [Stack Overflow question and answer on turning a price column into integers](https://stackoverflow.com/questions/44469313/price-column-object-to-int-in-pandas).

See how you can provide the example code there to the problem here.
"""

# Remove the punctuation from price column
car_sales["Price"] = car_sales["Price"].str.replace('[\$\,]','',regex=True).astype(float)

# Check the changes to the price column
car_sales["Price"]

# Remove the two extra zeros at the end of the price column



#already did

# Check the changes to the Price column



#already did

# Change the datatype of the Price column to integers




#it should be in float

# Lower the strings of the Make column
car_sales["Make"] = car_sales["Make"].str.lower()

"""If you check the car sales DataFrame, you'll notice the Make column hasn't been lowered.

How could you make these changes permanent?

Try it out.
"""

# Make lowering the case of the Make column permanent



#already did

# Check the car sales DataFrame
car_sales

"""Notice how the Make column stays lowered after reassigning.

Now let's deal with missing data.
"""

# Import the car sales DataFrame with missing data ("../data/car-sales-missing-data.csv")
car_sales_miss = pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/car-sales-missing-data.csv")

# Check out the new DataFrame
car_sales_miss

"""Notice the missing values are represented as `NaN` in pandas DataFrames.

Let's try fill them.
"""

# Fill the Odometer column missing values with the mean of the column inplace
car_sales_miss["Odometer"].fillna(car_sales_miss["Odometer"].mean(), inplace=True)

# View the car sales missing DataFrame and verify the changes
car_sales_miss

# Remove the rest of the missing data inplace
car_sales_miss.dropna(inplace=True)

# Verify the missing values are removed by viewing the DataFrame
car_sales_miss

"""We'll now start to add columns to our DataFrame."""

# Create a "Seats" column where every row has a value of 5
car_sales["Seats"] = 5
car_sales

# Create a column called "Engine Size" with random values between 1.3 and 4.5
# Remember: If you're doing it from a Python list, the list has to be the same length
# as the DataFrame
car_sales["Engine Size"] = [1.3,1.5,1.4,2.5,2.3,4.5,2.6,3.8,3.9,3.5]
car_sales

# Create a column which represents the price of a car per kilometer
# Then view the DataFrame
car_sales["Price Per KM"] =  (car_sales["Price"]/car_sales["Odometer (KM)"])*100
car_sales

# Remove the last column you added using .drop()
car_sales.drop("Price Per KM", axis=1)

# Shuffle the DataFrame using sample() with the frac parameter set to 1
# Save the the shuffled DataFrame to a new variable
suff = car_sales.sample(frac=1)
suff

"""Notice how the index numbers get moved around. The [`sample()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html) function is a great way to get random samples from your DataFrame. It's also another great way to shuffle the rows by setting `frac=1`."""

# Reset the indexes of the shuffled DataFrame
suff.reset_index(inplace=True)

"""Notice the index numbers have been changed to have order (start from 0)."""

# Change the Odometer values from kilometers to miles using a Lambda function
# Then view the DataFrame
suff.drop("index", axis=1, inplace=True)
suff["Odometer (KM)"] = (suff["Odometer (KM)"]*0.6).astype(int)
suff

# Change the title of the Odometer (KM) to represent miles instead of kilometers
suff.rename(columns={"Odometer (KM)":"Odometer Miles"})

"""## Extensions

For more exercises, check out the pandas documentation, particularly the [10-minutes to pandas section](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html).

One great exercise would be to retype out the entire section into a Jupyter Notebook of your own.

Get hands-on with the code and see what it does.

The next place you should check out are the [top questions and answers on Stack Overflow for pandas](https://stackoverflow.com/questions/tagged/pandas?sort=MostVotes&edited=true). Often, these contain some of the most useful and common pandas functions. Be sure to play around with the different filters!

Finally, always remember, the best way to learn something new to is try it. Make mistakes. Ask questions, get things wrong, take note of the things you do most often. And don't worry if you keep making the same mistake, pandas has many ways to do the same thing and is a big library. So it'll likely take a while before you get the hang of it.
"""